  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 5.0

  joint1_torque_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 200, i: 0, d: 0}
    
  joint2_torque_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 750, i: 0, d: 0}
    
  joint3_torque_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 750, i: 0, d: 0}
    
  joint4_torque_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 200, i: 0, d: 0}
